// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVbSQeK1i1Nug2c9NMLcFpq7-GRoaiOiQ',
    appId: '1:536854500452:web:29fdc67a039cc4ccf73b71',
    messagingSenderId: '536854500452',
    projectId: 'aldeebtech-1ec64',
    authDomain: 'aldeebtech-1ec64.firebaseapp.com',
    storageBucket: 'aldeebtech-1ec64.firebasestorage.app',
    measurementId: 'G-BLNCLGNKNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWhtV4GlVpoPMsNKKHlRRx4zYWF2fwh_Q',
    appId: '1:536854500452:android:3bad7c5852183165f73b71',
    messagingSenderId: '536854500452',
    projectId: 'aldeebtech-1ec64',
    storageBucket: 'aldeebtech-1ec64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBDBNfrOeNDmkzy_n-9jQ1t-cy8ikZmAw',
    appId: '1:536854500452:ios:fcabdca551b31f3ff73b71',
    messagingSenderId: '536854500452',
    projectId: 'aldeebtech-1ec64',
    storageBucket: 'aldeebtech-1ec64.firebasestorage.app',
    androidClientId:
        '536854500452-clold3nqrrpnghi2fcf5ujsd9i112pm6.apps.googleusercontent.com',
    iosClientId:
        '536854500452-i2b5lrsjpgevrgsf3le6m90t6lhq4nf5.apps.googleusercontent.com',
    iosBundleId: 'com.example.storeController',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBDBNfrOeNDmkzy_n-9jQ1t-cy8ikZmAw',
    appId: '1:536854500452:ios:fcabdca551b31f3ff73b71',
    messagingSenderId: '536854500452',
    projectId: 'aldeebtech-1ec64',
    storageBucket: 'aldeebtech-1ec64.firebasestorage.app',
    androidClientId:
        '536854500452-clold3nqrrpnghi2fcf5ujsd9i112pm6.apps.googleusercontent.com',
    iosClientId:
        '536854500452-i2b5lrsjpgevrgsf3le6m90t6lhq4nf5.apps.googleusercontent.com',
    iosBundleId: 'com.example.storeController',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVbSQeK1i1Nug2c9NMLcFpq7-GRoaiOiQ',
    appId: '1:536854500452:web:69ee9cc6a59f5a87f73b71',
    messagingSenderId: '536854500452',
    projectId: 'aldeebtech-1ec64',
    authDomain: 'aldeebtech-1ec64.firebaseapp.com',
    storageBucket: 'aldeebtech-1ec64.firebasestorage.app',
    measurementId: 'G-H9L06ZJS8Y',
  );
}
